### ISSUE TITLE
SaveChartAs bug

### ISSUE THREAD

**Issue by jdh30** [fslaborg/FSharp.Charting#38]
Calling a chart's SaveChartAs instance method without first calling ShowChart causes it to silently emit blank images.

**Comment by dsyme** [comment]
Fixed in #75

**Comment by brianary** [comment]
Still getting an error:

```fsharp
// Using a paket.dependencies file to install FSharp.Charting.
//   see http://fsprojects.github.io/Paket/
#I @".\packages\FSharp.Charting\lib\net40"
#r "FSharp.Charting"
open FSharp.Charting

Chart.Save @"piechart.png" <| Chart.Pie(data=["A",3;"B",1;"C",1])
```

Result (run with Alt+Enter within Visual Studio):

```text
System.InvalidOperationException: Starting a second message loop on a single thread is not a valid operation. Use Form.ShowDialog instead.
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at FSharp.Charting.Chart.Save(String filename, GenericChart chart) in C:\GitHub\fslaborg\FSharp.Charting\src\FSharp.Charting.fs:line 3132
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in A:\Tasks\temp.fsx:line 7
```

**Comment by brianary** [comment]
This works OK though:

```fsharp
// Tip: Create a paket.dependencies file to install FSharp.Data.SqlClient and FSharp.Charting.
//   see http://fsprojects.github.io/Paket/
#I @".\packages\FSharp.Charting\lib\net40"
#r "FSharp.Charting"
open FSharp.Charting
// Needed for FSharp.Charting's ShowChart() method.
#r "System.Windows.Forms.DataVisualization"

(Chart.Pie(data=["A",3;"B",1;"C",1])).SaveChartAs("piechart.png",ChartTypes.ChartImageFormat.Png)
```

**Comment by brianary** [comment]
Adding `ShowChart()` back in saves a chart that isn't blank:

```fsharp
// Tip: Create a paket.dependencies file to install FSharp.Data.SqlClient and FSharp.Charting.
//   see http://fsprojects.github.io/Paket/
#I @".\packages\FSharp.Charting\lib\net40"
#r "FSharp.Charting"
open FSharp.Charting
// Needed for FSharp.Charting's ShowChart() method.
#r "System.Windows.Forms.DataVisualization"

let c = Chart.Pie(data=["A",3;"B",1;"C",1])
c.ShowChart()
c.SaveChartAs(@"H:\piechart.png",ChartTypes.ChartImageFormat.Png)
```

**Comment by simra** [comment]
I'll investigate and see whether Form.ShowDialog will implicitly launch an event loop. The alternative is to wrap a try block around the Application.Run call and fall back to ShowDialog, which seems clumsy.

**Comment by brianary** [comment]
Is it likely that this library will be able to support automation, such as
a scheduled script to generate an email with charts?

**Comment by simra** [comment]
Yes, I have a workflow that does exactly this. Is there something specific that you feel is missing?

-----Original Message-----

**Comment by brianary** [comment]
No, I was just concerned that the ShowChart call would block the process,
but it sounds like this is not the case.

**Comment by simra** [comment]
Everything works for me in fsi and .exe if I use f.ShowDialog instead of Application.Run.  Checking on the other thread to see if there might be any known issues using ShowDialog.  It's a one-line change in Chart.Save.

**Comment by brianary** [comment]
OK, sounds good.
